#ifndef _DEF_CE_HEADER_TEENSY_
#define _DEF_CE_HEADER_TEENSY_

#define _TEENSY_RX1 0
#define _TEENSY_TX1 1
#define _TEENSY_GPIO_2 2
#define _TEENSY_GPIO_3 3
#define _TEENSY_GPIO_4 4
#define _TEENSY_GPIO_5 5
#define _TEENSY_GPIO_6 6
#define _TEENSY_GPIO_7 7
#define _TEENSY_GPIO_8 8
#define _TEENSY_GPIO_9 9
#define _TEENSY_SPI_CS 10
#define _TEENSY_SPI_DOUT 11
#define _TEENSY_SPI_DIN 12
#define _TEENSY_SPI_SCK 13
#define _TEENSY_A0_GPIO_14 14
#define _TEENSY_A1_GPIO_15 15
#define _TEENSY_A2_GPIO_16 16
#define _TEENSY_A3_GPIO_17 17
#define _TEENSY_SDA0 18
#define _TEENSY_SCL0 19
#define _TEENSY_A6_GPIO_20 20
#define _TEENSY_A7_GPIO_21 21
#define _TEENSY_A8_GPIO_22 22
#define _TEENSY_A9_GPIO_23 23

#define CE_SPI_MOSI_GPIO_0 _TEENSY_SPI_DOUT
#define CE_SPI_MISO_GPIO_1 _TEENSY_SPI_DIN
#define CE_SPI_CLK_GPIO_2 _TEENSY_SPI_SCK
#define CE_SPI_CS_GPIO_3 _TEENSY_SPI_CS
#define CE_USART_RX_GPIO_4 _TEENSY_TX1
#define CE_USART_TX_GPIO_5 _TEENSY_RX1
#define CE_I2C_SCLK_GPIO_6 _TEENSY_SCL0
#define CE_I2C_SDAT_GPIO_7 _TEENSY_SDA0
#define CE_AIO_0_GPIO_8  _TEENSY_A0_GPIO_14
#define CE_AIO_1_GPIO_9 _TEENSY_A1_GPIO_15 
#define CE_AIO_2_GPIO_10 _TEENSY_A2
#define CE_AIO_3_GPIO_11 _TEENSY_A3

#endif
